#------------------------------------------------- Begin role users ----------------------------------------------------#
use_keys: tuan-svr

users_add:
  - { user: 'tuanpv', password: '{{ password_manage }}', email: 'vantuanpham95@gmail.com', mobile: '0984266846' }

users_add_sudo:
  - { user: 'tuanpv', password: '{{ password_manage }}', email: 'vantuanpham95@gmail.com', mobile: '0984266846' }

users_del_sudo:
#  - { user: 'tuanpv', password: '{{ password_manage }}', email: 'vantuanpham95@gmail.com', mobile: '0984266846' }

# Khai báo user muốn xoá
users_del:
#  - { user: 'tuanpv', password: '{{ password_manage }}', email: 'vantuanpham95@gmail.com', mobile: '0984266846' }

# Khai báo allow user được phép ssh
ssh_allow_users: "tuanpv"


#------------------------------------------------- End role users ------------------------------------------------------#


#------------------------------------------------- Begin role sysctl ---------------------------------------------------#
net_ipv4_ip_forward: '1'


#------------------------------------------------- End role sysctl -----------------------------------------------------#


#------------------------------------------------- Begin role policy for Ubuntu ----------------------------------------#
#------------------------------------------------- Section 01 ----------------------------------------------------------#
# Cấu hình update cache và upgrade các gói
# yes: là enable
# no: là disable
apt_update: yes
apt_upgrade: no

#------------------------------------------------- End role policy for Ubuntu ------------------------------------------#
#------------------------------------------------- Begin role iptables ------------------------------------------------#
# Bật hoặc tắt synproxy
synproxy: no

# Các port sẽ cấu hình synproxy
sync_port:
  - 8888
  - 80
  - 443

# Mở các port tcp cho phép kết nối đến
tcp_port:
  - 3306
  - 3307
#  - 9100 # Prometheus Node Exporter

# Các server được phép kết nối với nhau
ip_allow_vrrp:
#  - 192.168.1.10
#  - 192.168.1.20

# Các server monitor
#ip_allow_nrpe:
#  - 192.168.2.97
#  - 123.30.170.97
#  - 10.3.17.116
#nrpe_port: 5666
#------------------------------------------------- End role iptables --------------------------------------------------#


#------------------------------------------------- End role Prometheus Exporter ------------------------------------------------#
# Haproxystats
haproxysocket_dir: /var/run/haproxy

#------------------------------------------------- End role Prometheus Exporter ------------------------------------------------#
